### PR TITLE
64bit support now implemented completely

### PR DESCRIPTION
**Pull request by caspahouzer**
tested with ti-64

com.sideshowcoder.jpgcompressor:0.5.3@project armv7 i386 x86_64 arm64

### CODE REVIEW

**Comment by caspahouzer** [comment]
Sorry for this hopping PR

**Comment by sideshowcoder** [comment]
Sorry I'm just back from vacation. Is the current state not working yet? I'm happy to integrate your changes in this case do you mind removing the files which are in gitignore so? I feel like there are files which are part of actual user settings in this PR that I don't feel like should be present in the main repository.

**Comment by caspahouzer** [comment]
Yes, have it in a 64bit production app, already released by Apple. This works now as expected. You can merge completely

**Comment by tvanmil** [comment]
Hi guys, 
Thanks for your effort! Is it possible to build a new distribution file including the 64bit functionality? I'm not that proficient in building a module myself, so that would help me out a lot.

**Comment by sideshowcoder** [comment]
@tvanmil sure thing, I'm going to make a build tomorrow and push it up.

**Comment by sideshowcoder** [comment]
This has been merged as 3b41c3a

**Comment by sideshowcoder** [comment]
@tvanmil I created a new build based on this PR see https://github.com/sideshowcoder/jpgcompressor/releases it is not updated to SDK 4.1.0 which is the latest, yet as there have been more changes than I feel comfortable with fixing right now. Hope this works for you.

**Comment by tvanmil** [comment]
Thanks guys, works perfectly in 4.0.0 at least. When I can make time I'll look into this module, I could use some extra functionality. E.g. a setCompressFactor function, as I don't always know the original file size (depends on device camera in my usecase) and I want to compress it depending on the original size instead of one fixed target size. Hopefully I'll get around to it soon...

**Comment by sideshowcoder** [comment]
Go for it, I'm happy to merge and can give you access to the repo if needed as well.

**Pull request closed without merging**
